name: 02 - Workflow Events
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
        types: [opened, synchronize, reopened]
    schedule:
        - cron: '0 0 * * *' # Runs every day at midnight
    workflow_dispatch:
        inputs:
            name:
                description: 'Name to display in the workflow'
                required: true
                default: 'World'

jobs:
    echo:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - name: Show the trigger
              run: 'echo "The workflow was triggered by the following event: ${{ github.event_name }}"'