name: 02 - Workflow Events
on: |
    push
    pull_request
    schedule:
        - cron: '0 0 * * *' # Runs every day at midnight
    workflow_dispatch:
        inputs:
            name:
                description: 'Vishwa Sai Challa'
                required: true
                default: 'World'
    

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger
              run: 'echo "The workflow was triggered by the following event: ${{ github.event_name }}"'