name: 05 - 1 - Event Filters and Activity Types
on:
  pull_request:
    types: [opened, synchronize]
    branches: main
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Print steps
        run: 'echo "Action type: ${{ github.event.action || github.event_name }}; base branch is main"'
